---
version: 2
deployment:
  engine: git

tasks:
  # Install dependencies including Tailwind CSS
  - name: Install dependencies
    action: npm install tailwindcss

directories:
  include:
    # Include all directories except .env
    - public_html
    - src
    - assets
    - styles
  exclude:
    # Exclude the .env file
    - .env

hooks:
  # Post-deployment hook
  - trigger: post_deployment
    actions:
      # Display a message after deployment
      - system:
          - echo "Deployment completed successfully."
